// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dggglm
List dggglm(NumericMatrix A, NumericMatrix B, NumericVector d, const int NB);
RcppExport SEXP _msrat_dggglm(SEXP ASEXP, SEXP BSEXP, SEXP dSEXP, SEXP NBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< const int >::type NB(NBSEXP);
    rcpp_result_gen = Rcpp::wrap(dggglm(A, B, d, NB));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_msrat_dggglm", (DL_FUNC) &_msrat_dggglm, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_msrat(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
